# Generated by Django 4.1.1 on 2022-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_filament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
