# Generated by Django 4.1.1 on 2022-09-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_filament_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='material',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PLA+', 'PLA+'), ('PTEG', 'PTEG'), ('ABS', 'ABS'), ('NY', 'Nylon')], default='PLA', max_length=4),
        ),
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print', models.CharField(max_length=50)),
                ('print_time', models.IntegerField()),
                ('filament', models.CharField(choices=[('PLA', 'PLA'), ('PLA+', 'PLA+'), ('PTEG', 'PTEG'), ('ABS', 'ABS'), ('NY', 'Nylon')], default='PLA', max_length=4)),
                ('completed', models.CharField(choices=[(1, 'Success'), (0, 'Failure')], default=1, max_length=1)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.printer')),
            ],
        ),
    ]
