# Generated by Django 4.1.1 on 2022-09-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_filament_material_prints'),
    ]

    operations = [
        migrations.AddField(
            model_name='prints',
            name='layer_height',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=3),
        ),
        migrations.AddField(
            model_name='prints',
            name='nozzle_size',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=3),
        ),
        migrations.AddField(
            model_name='prints',
            name='nozzle_temp',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='prints',
            name='other_settings',
            field=models.TextField(default='Additional slicer settings', max_length=250),
        ),
        migrations.AlterField(
            model_name='filament',
            name='diameter',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=3),
        ),
    ]
