# Generated by Django 4.1.1 on 2022-09-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_prints_layer_height_prints_nozzle_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prints',
            new_name='Print',
        ),
    ]
