# Generated by Django 4.1.1 on 2022-09-22 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_prints_print'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='print',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
