# Generated by Django 4.1.1 on 2022-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_print_options_print_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='completed',
            field=models.CharField(choices=[('1', 'Success'), ('0', 'Failure')], default='1', max_length=1),
        ),
    ]
