# Generated by Django 4.1.1 on 2022-10-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_print_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='printer',
        ),
        migrations.AddField(
            model_name='print',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='prints',
            field=models.ManyToManyField(to='main_app.print'),
        ),
        migrations.AddField(
            model_name='printer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='printer',
            name='print_materials',
        ),
        migrations.AddField(
            model_name='printer',
            name='print_materials',
            field=models.ManyToManyField(to='main_app.filament'),
        ),
    ]
